steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package','-Dmaven.test.skip=true','-Djar.finalName=myapp']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'target/myapp.jar', 'gs://dataset2023/myapp.jar']
