steps:
- name: gcr.io/cloud-builders/mvn
  args: ['clean', 'install']
- name: gcr.io/cloud-builders/mvn
  args: ['-Pdataflow-runner', 'compile', 'exec:java', '-Dexec.mainClass=WordCount', '-Dexec.args=--project=learning-313419 --gcpTempLocation=gs://dataset2023/temp/ --output=gs://dataset2023/output --runner=DataflowRunner --region=us-central1']
